apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kubernetes-challenge
type: Opaque
data:
  POSTGRES_USER: #base64 do usuário — gerar localmente
  POSTGRES_PASSWORD: #base64 da senha — gerar localmente